variables:
    APP_NAME_FRONT: annotrieve-nginx
    APP_NAME_BACK: annotrieve-fastapi

stages: 
  - build
  - deploy

build_containers:
  only:
    - main

  tags:
    - shell
    - monstre

  stage: build
  image: docker:latest

  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

  script:
    - docker build -t gitlab.hpc.crg.es:5005/monstre/annotrieve/$APP_NAME_FRONT ./front
    - docker push gitlab.hpc.crg.es:5005/monstre/annotrieve/$APP_NAME_FRONT
    - docker build -t gitlab.hpc.crg.es:5005/monstre/annotrieve/$APP_NAME_BACK ./server
    - docker push gitlab.hpc.crg.es:5005/monstre/annotrieve/$APP_NAME_BACK

deploy_containers:
  stage: deploy
  tags:
    - shell
    - monstre
  script:
    - cat $ENV_FILE > .env
    - docker-compose down -v
    - docker-compose up -d
